# Generated by Django 4.1.6 on 2023-02-15 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.CharField(max_length=20)),
                ('Maxtemp', models.IntegerField()),
                ('Mintemp', models.IntegerField()),
                ('Precipitation', models.IntegerField()),
                ('Station_ID', models.CharField(max_length=20)),
            ],
            options={
                'unique_together': {('Date', 'Station_ID')},
            },
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Station_ID', models.CharField(max_length=20)),
                ('Date', models.CharField(max_length=20)),
                ('AvgMaxtemp', models.IntegerField()),
                ('AvgMintemp', models.IntegerField()),
                ('TotalAccPrecipitation', models.IntegerField()),
            ],
            options={
                'unique_together': {('Date', 'Station_ID')},
            },
        ),
    ]
